spring:
  application:
    name: orbit-backend

  spring:
  application:
    name: orbit-backend

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true